### PR TITLE
Last-Modified header and If-Modified-Since handling

### PR DESCRIPTION
**Pull request by heroldus**
We extented the plugin to handle If-Modified-Since header to send "304 Not Modified" request back to the client. You may also interested in the spec file or our extent function.

Have fun,
Sebastian

### CODE REVIEW

**Comment by mikeroque** [comment]
Thanks for the reply, @heroldus.

>Is it reproducible for the same file or does it occur randomly?

Yes, it happens on the same file consistently.  Here's [an example where it's broken](http://www.primagames.com/dims3/PRIMA/resize/1600x800/http://www.primagames.com/media/gn/images/eguides/backgrounds/lego-batman-bg.jpg):
`Last-Modified:Mon, 28 Sep %96939 04:26:27 GMT`

Here's [the image directly from Apache](http://www.primagames.com/media/gn/images/eguides/backgrounds/lego-batman-bg.jpg), and the header is correct:
`Last-Modified:Fri, 24 Oct 2014 18:30:40 GMT`

**Comment by mikeroque** [comment]
It looks like the issue only occurs when with using [the remote image URL format](http://www.primagames.com/dims3/PRIMA/resize/1600x800/http://www.primagames.com/media/gn/images/eguides/backgrounds/lego-batman-bg.jpg), so I've changed our image paths to use the suffix URL pattern on image paths [like this](http://www.primagames.com/media/gn/images/eguides/backgrounds/lego-batman-bg.jpg/PRIMA/resize/1600x800/), which returns the `Last-Modified` header properly.

**Comment by heroldus** [comment]
This makes sense, because for remote connections the code cannot determine the last modification date via stat. It's for local files only. For remote connections we should forward the last modification header if it's included in the response header, but this exceeds my C programming skills. Sorry.

**Comment by mikeroque** [comment]
No worries.  Thanks for the response! :)

**Comment by beetlebugorg** [comment]
> Cause there seems not to be an "official" `image/jpg` MIME type, only `image/jpeg` (see eg: https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types or `grep image/jp /etc/mime.types`). Some clients/viewers (looking at you, iOS) take that overly serious and don't work with `image/jpg`

What version of Imagemagick are you using? In my tests it always returns the format as `jpeg`. I wonder if it could also be related to libjpeg library?

**Pull request closed without merging**
